### ISSUE TITLE
Request for Hardware and Runtime Information

### ISSUE THREAD

**Issue by mwalmer-umd** [minghchen/CARL_code#8]
Hello, if possible, could the authors provide recommended hardware (CPU/GPU counts) and expected runtimes for the jobs described in the "Training" section? I am attempting to run these jobs and data loading seems to be a major bottleneck for my runtime. For example, training one epoch on Penn Action is taking about 30 minutes each. Is this normal?

**Comment by minghchen** [comment]
In my paper, I train the model on 4 P40 or 4 V100 GPUs. 
Considering you might not have access to V100 GPU, I also test the code on one 1080ti GPU with the following command.
`python -m torch.distributed.launch --nproc_per_node 1 train.py --workdir ~/datasets --cfg_file ./configs/scl_transformer_action_config.yml --logdir ~/tmp/scl_transformer_action_logs`
It takes about 10 minutes for one epoch.
CPU info: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz. 12 Cores.

**Comment by mwalmer-umd** [comment]
Thanks!
